### ISSUE TITLE
Update database without updating index?

### ISSUE THREAD

**Issue by MikkyX** [teamtnt/laravel-scout-tntsearch-driver#124]
I have a TNTSearch index which is 4.4 million rows containing just company name and ID (since this is all we search against)

Whenever updating any row in this table the index is updated. Understandable, but we are modifying three columns which aren't part of the index, and updating the index slows this particular import process right down. We have no need to update the index here - is there a way to update an Eloquent Model without updating the TNTSearch index?

**Comment by stokic** [comment]
Hm this is really a Laravel Scout question, because you'll have the same problem regardless of the search driver used :/

I think a good solution would be to either override default Searchable trait similar to this https://gist.github.com/Harti/ec1fcd28b162bbb2e7fe06ce2df22275 with an added twist of checking if the X, Y, Z field were updated and then deciding if it should be updated or not...

But if speed is your main concern then I would suggest using Queues for Scout which offloads index updates so your users wont feel it happening https://laravel.com/docs/5.5/scout#queueing

**Comment by MikkyX** [comment]
You make a fair point, apologies for putting my question here. I'll look into what solutions Scout offers for this, thank you :)
