### ISSUE TITLE
OrderBY in constraint is canceled by map() method

### ISSUE THREAD

**Issue by marcoskubis** [teamtnt/laravel-scout-tntsearch-driver#168]
Any orderBy added to query constraint is canceled by these lines of code:

https://github.com/teamtnt/laravel-scout-tntsearch-driver/blob/master/src/Engines/TNTSearchEngine.php#L236

```
...

return collect($results['ids'])->map(function ($hit) use ($models) {
    if (isset($models[$hit])) {
        return $models[$hit];
    }
})->filter()->values();

...
```

Why we need this map and filter? Any sort is reseted by this piece of code.

**Comment by thoresuenert** [comment]
We need this map here because otherwise the ordering gets lost.

tntsearch returns results in a specific relevant order to the search term, without this map this relevant ordering gets lost.

**Comment by marcoskubis** [comment]
I understood. So it's better that it stay this way. Thanks for explanation @thoresuenert.

**Comment by michaelklopf** [comment]
I just ran into a similar problem, where having orderBy would be nice to have because we don't have to sort on the whole collection and make use of the db query.

Luckily similar to the where statements, Laravel Scout supports orderBy.

I found a way to support that feature, as seen in the following Gist:

https://gist.github.com/michaelklopf/802ad53bd3caedce115c6f23b76e569f

The getBuilder() function looks clumsy, but I had don't have a clue yet if that map-reduce pattern here is necessary.

I'll make a PR for that feature, but maybe someone would like to test it with the Gist version.
