### ISSUE TITLE
Bug with Laravel Scout v6.1.3 update

### ISSUE THREAD

**Issue by Dylan-Chapman** [teamtnt/laravel-scout-tntsearch-driver#215]
(For more details/discussion: [https://github.com/laravel/scout/issues/339](https://github.com/laravel/scout/issues/339))

Lazy loading relationships is no longer working with the latest Laravel Scout. They recommended I open a thread in this repo. They thought it may be related to: [https://github.com/teamtnt/laravel-scout-tntsearch-driver/blob/master/src/Engines/TNTSearchEngine.php#L197-L206](https://github.com/teamtnt/laravel-scout-tntsearch-driver/blob/master/src/Engines/TNTSearchEngine.php#L197-L206).

The problem is that
```php
MyModel::search('myQuery')->get()->load('myRelation');
```
returns the error 
```
Method Illuminate\Support\Collection::load does not exist.
```

**Comment by ahkmunna** [comment]
Having the same issues. Sometime the `get()` returns 

`Illuminate\Support\Collection`

and sometimes

`Illuminate\Database\Eloquent\Collection`

as `Illuminate\Support\Collection` don't have load method.

**Comment by renatosistemasvc** [comment]
same problem here

**Comment by renatosistemasvc** [comment]
@Dylan-Chapman Can you solve this?

**Comment by Dylan-Chapman** [comment]
@renatosistemasvc Nope, I had to revert to Laravel Scout v6.1.1 until this is fixed.

**Comment by Dylan-Chapman** [comment]
It's not this package you need to revert, it's Scout. Sending the teamtnt folder won't help. Just lock Scout in your composer json: `"laravel/scout": "6.1.1"` and run a composer install.

**Comment by renatosistemasvc** [comment]
@Dylan-Chapman your solution worked! Thank you friend!

**Comment by ncrewsSouthern** [comment]
I was just about to open a support ticket on this same issue, then found this.  

I've been looking through code and if I do the following 
```
$results = Collection::make( Entity::search( $query )->get() );
$results->load( 'relationship_name');
```
it works as a temporary fix.  Reviewing code for this project I found the following. 

https://github.com/teamtnt/laravel-scout-tntsearch-driver/blob/655d6ead9192d49c58dd85c9de6e53ea5d9cbe25/src/Engines/TNTSearchEngine.php#L201-L206

If I change the linked lines to 
```
return Collection::make($results['ids'])->map(function ($hit) use ($models) {
            if (isset($models[$hit])) {
                return $models[$hit];
            }
        })->filter()->values();
```


It fixes my issue.  I get an instance of "Illuminate\Database\Eloquent\Collection" instead of "Illuminate\Support\Collection" which is what is returned by `collect()`

 I was about to work on a PR as this looked like a fix but saw the following comment so left it be as there could be other implications of this change I'd not considered.
> It's not this package you need to revert, it's Scout. Sending the teamtnt folder won't help. Just lock Scout in your composer json: `"laravel/scout": "6.1.1"` and run a composer install.

**Comment by Dylan-Chapman** [comment]
I just tested, and it seems like this actually broke in v6.1.2, which means it's likely caused by [this pull request](https://github.com/laravel/scout/pull/334). So, I think as long as you cross-check any changes from that pull request, it will probably be fine.

**Comment by ahkmunna** [comment]
This issue still exist in latest version of tntsearch and laravel 6.x.

**Comment by ahkmunna** [comment]
Any update regarding this issue?
