### ISSUE TITLE
Index does not exist.

### ISSUE THREAD

**Issue by RyanThompson** [teamtnt/laravel-scout-tntsearch-driver#23]
I find when saving an entry for the first time without manually making the index I get this error.

It really should auto-create the index (upon second attempt it works fine). Creating indexes in not in the Scout behavior and as such should be done in the background.

Thoughts?

**Comment by nticaric** [comment]
This is very strange because the IndexNotFound exception can only occur if a search was done, otherwise when saving an entry we have a check if the index exists and if not, to create it. Take a look at:

https://github.com/teamtnt/laravel-scout-tntsearch-driver/blob/master/src/Engines/TNTSearchEngine.php#L164
