### ISSUE TITLE
Whole field not being matched

### ISSUE THREAD

**Issue by ge022** [teamtnt/laravel-scout-tntsearch-driver#237]
I have the following field in my toSearchableArray():
`'Birth' => date('m/d/Y', strtotime($this->Birth))`
An example date to be indexed is "06/06/1966". When I search this exact string, no results match, but if I search something like "06 06 1966" then I get the match.
My searchBoolean is set to true. What's going on?

**Comment by nticaric** [comment]
The problem with dates is that the default tokenizer breaks them into numbers. What you could do is write your own tokenizer function or to use the 
https://github.com/teamtnt/tntsearch/blob/master/src/Support/ProductTokenizer.php

Since, you're using laravel scout you'll have to do the indexing manually via TNTSearch package

**Comment by ge022** [comment]
@nticaric I enabled fuzziness, and that fixed the issue.
