### ISSUE TITLE
Query String

### ISSUE THREAD

**Issue by i6media** [teamtnt/laravel-scout-tntsearch-driver#279]
Is it possible to search a string for only one column? For example `Model::search("name(test)")`? Currently it's quite limited and will search through all columns am I right?

**Comment by stokic** [comment]
All searchable, but that’s a question for Scout not particular driver

**Comment by i6media** [comment]
I think it **is** a question for the driver. Laravel Scout itself doesn't offer the posibility to specify column searches. It just passes a search string to the driver. If you look at the [Elastic driver](https://github.com/babenkoivan/elastic-scout-driver#basic-usage) for Scout, you can see that it offers a query string.

**Comment by stokic** [comment]
yes, it could be done on the driver level but what I'm saying is that it should be on the Scout level, otherwise all drivers will implement their own logic, and swapping drivers will become pain in the ass :) 

don't know how Taylor feels about that though...

it might be something that we could introduce in a way Elastic does if Scout doesn't introduce something similar soon...

**Comment by i6media** [comment]
If it's not achievable by scout, is it possible to bypass scout and use TNTSearch class directly?
