### ISSUE TITLE
[ErrorException] Empty row packet body

### ISSUE THREAD

**Issue by rmff** [teamtnt/laravel-scout-tntsearch-driver#46]
Did anyone receive "[ErrorException] Empty row packet body" on use artisan tntsearch:import "model..." ?

This occurs after processe more than 36000 rows, every time in same point.

Is there an way to debug this?

**Comment by nticaric** [comment]
This might happen if you're operating on a MyISAM table. The tntsearch:import command tries to read the result set unbuffered which means it will lock the whole table with a shared lock. The error you mentioned will occur if you try to do some updates on the table in the meanwhile.

What solves the problem is changing the table type to InnoDB, since that Engine uses row-level instead of table-level locks. Another solution is to use `php artisan scout:import Model`

**Comment by rmff** [comment]
@nticaric it's a InnoDB table. 
I tried to use scout:import before, but it's very very slow to process. I have more than 500K rows and toke more than 5 hours to process all rows.

**Comment by MikkyX** [comment]
I'm having this issue with a 4 million row InnoDB table, usually around the million row mark. I'm only trying to index the ID and name from the table as these are all I need to search. As @rmff has already mentioned, scout:import is too slow to be a workable alternative.

**Comment by nticaric** [comment]
@MikkyX can you try with this solution https://stackoverflow.com/a/47181622/555983

**Comment by MikkyX** [comment]
Trying now, thanks @nticaric - I should point out that it imported flawlessly _online_ and that searches are absolutely LIGHTNING quick :)

**Comment by xsmartweb** [comment]
I having same errors after proceed 564000 rows. 
My table type is InnoDb.

**Comment by stokic** [comment]
@xsmartweb have you tried https://stackoverflow.com/questions/3780521/strange-mysql-error-empty-row-packet-body-when-using-mysql-fetch-object-php-5/47181622#47181622 ?

What is your table structure? What kind of data is in there? Give us more information so that we can help. In general, it's a mysql problem not TNTSearch... Many people have much much larger tables indexed so it's probably some mysql config issue on your server...
