### ISSUE TITLE
Unsupported driver [sqlsrv]... Is it possible to fix this?

### ISSUE THREAD

**Issue by JeanHules** [teamtnt/laravel-scout-tntsearch-driver#48]
I am using a MSSQL DB with an Ubuntu based Laravel application. Is it possible to using the sqlsrv driver with TNT? If so, how?

**Comment by nticaric** [comment]
The usage of scout should not be different than for any other database.

**Comment by gdesoto** [comment]
I was getting the same error using a MS SQL Server. I'm just dipping my toes in to laravel, scout, and tntsearch, but here's what I found... 

TNTSearch uses their own [database connectors](https://github.com/teamtnt/tntsearch/tree/master/src/Connectors). They do not include one for MSSQL. I didn't see much of a difference between Laravel's and TNTSearch, so I just did the following changes to [TNTIndexer.php](https://github.com/teamtnt/tntsearch/blob/master/src/Indexer/TNTIndexer.php).

Near the top of the file I imported Laravel's SqlSrv connector by adding the following:
```php
use Illuminate\Database\Connectors\SqlServerConnector;
```

I then modified the following "createConnector" method from:
```php
public function createConnector(array $config)
    {
        if (!isset($config['driver'])) {
            throw new Exception('A driver must be specified.');
        }

        switch ($config['driver']) {
            case 'mysql':
                return new MySqlConnector;
            case 'pgsql':
                return new PostgresConnector;
            case 'sqlite':
                return new SQLiteConnector;
            case 'filesystem':
                return new FileSystemConnector;
        }
        throw new Exception("Unsupported driver [{$config['driver']}]");
    }
```
to
```php
public function createConnector(array $config)
    {
        if (!isset($config['driver'])) {
            throw new Exception('A driver must be specified.');
        }

        switch ($config['driver']) {
            case 'mysql':
                return new MySqlConnector;
            case 'pgsql':
                return new PostgresConnector;
            case 'sqlite':
                return new SQLiteConnector;
            case 'filesystem':
                return new FileSystemConnector;
            case 'sqlsrv':
                return new SqlServerConnector;
        }
        throw new Exception("Unsupported driver [{$config['driver']}]");
    }
```

Since I didn't make and changes to the laravel scout tntsearch driver, this is probably an issue for the main tntsearch repo.

**Comment by pedropanos** [comment]
+1

**Comment by nticaric** [comment]
@pedropanos can you try `composer update` to get the latest version of TNTSearch

Please let us know if it works for you

**Comment by pedropanos** [comment]
WOW! Now it works perfectly. Thank you very much @nticaric

**Comment by nticaric** [comment]
@pedropanos you're welcome
