### ISSUE TITLE
Display results with a WHERE CLAUSE 

### ISSUE THREAD

**Issue by mourareaupro** [teamtnt/laravel-scout-tntsearch-driver#69]
Hello , 

I try to display my search results with a WHERE condition but the condition have no effect with TNT Search . i know that this feature is not include in the driver actually but today there is a solution for this ? maybe with filters method ? 

Best regards

**Comment by pmall** [comment]
Not working here to. Where method has no effect.

**Comment by getupkid** [comment]
As far as I am aware, you can not do a WHERE on the fetch from the index. However, since it creates a collection you could technically filter it afterwards, have you tried that?

Example:
// Get all users that match a search query from the index
$users = User::search($query)->get();

// Filter it down to only users created today
$users->filter(function ($value, $key) {
                return $value['created_at'] >= Carbon::today()->toDateString();
            });

**Comment by mourareaupro** [comment]
thanks ! i saw the update with the where clause but it's seems has no effect 

return User::search($request->get('q'))
            ->where('structure_id' , '=' , '4')
            ->get();

i made sure to update my composer before trying this

**Comment by nticaric** [comment]
Have you tried `->where('structure_id', 4)` without the `=` sign
